name: Deploy to Render

on:
  push:
    branches:
      - main  # deploy when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chatbot_drf:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/chatbot_drf:latest
