name: Deploy to Render

on:
  push:
    branches:
      - main  # Deploy when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Optional: Run Tests ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies for Tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: |
          python manage.py test || exit 1

      # ---------- Docker Build & Push ----------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/chatbot_drf
          VERSION_TAG=${{ github.run_number }}

          echo "Building image: $IMAGE_NAME:$VERSION_TAG"
          docker build -t $IMAGE_NAME:$VERSION_TAG -t $IMAGE_NAME:latest .

          echo "Pushing image..."
          docker push $IMAGE_NAME:$VERSION_TAG
          docker push $IMAGE_NAME:latest

      # ---------- Trigger Render Deployment ----------
      - name: Trigger Render Deployment
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
